In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import datetime
%matplotlib inline

In [6]:
import requests
import json
import pickle
import os
import csv
from datetime import datetime

In [7]:
path = 'C:\\python\\datasets'
os.chdir(path)

In [8]:
df_New_Cases = pd.read_csv('New Cases - vaccination.csv')
df_New_Death = pd.read_csv('New Death - vaccination.csv')
df_Severe_Cases = pd.read_csv('Severe Cases - vaccination.csv')
df_Culmulativ = pd.read_csv('Culmulativ pecentage of vaccines.csv')

In [9]:
df_New_Cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 888 entries, 0 to 887
Data columns (total 8 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Date                                     888 non-null    object
 1   age group                                888 non-null    object
 2   New cases vaccinated                     888 non-null    int64
 3   New cases expired Vaccination            888 non-null    int64
 4   New cases Not vaccinated                 888 non-null    int64
 5   New cases vaccinated per 100k            888 non-null    float64
 6   New cases expired Vaccination  per 100k  888 non-null    float64
 7   New cases Not vaccinated per 100k        888 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 55.6+ KB

In [10]:
df_New_Cases['Date'] = pd.to_datetime(df_New_Cases['Date'],format = '%d-%m-%Y')
df_New_Death['Date'] = pd.to_datetime(df_New_Death['Date'],format = '%d-%m-%Y')
df_Severe_Cases['Date'] = pd.to_datetime(df_Severe_Cases['Date'],format = '%d-%m-%Y')
df_Culmulativ['Date'] = pd.to_datetime(df_Culmulativ['Date'],format = '%d-%m-%Y')

In [11]:
df_New_Cases.head(6)

,Date,age group,New cases vaccinated,New cases expired Vaccination,New cases Not vaccinated,New cases vaccinated per 100k,New cases expired Vaccination per 100k,New cases Not vaccinated per 100k
0,2021-01-17,60+,0,0,243,0.0,0.0,51.4
1,2021-01-17,All population,1,0,4729,3.9,0.0,66.3
2,2021-01-17,0-59,1,0,4450,6.4,0.0,66.9
3,2021-01-18,All population,6,0,8738,13.2,0.0,123.8
4,2021-01-18,0-59,2,0,8309,7.9,0.0,126.0
5,2021-01-18,60+,4,0,347,19.8,0.0,74.5

In [12]:
df = df_New_Cases.merge(df_New_Death,on = ['Date','age group'])

In [13]:
df1 = df.merge(df_Severe_Cases,on = ['Date','age group'])

In [14]:
df1

,Date,age group,New cases vaccinated,New cases expired Vaccination,New cases Not vaccinated,New cases vaccinated per 100k,New cases expired Vaccination per 100k,New cases Not vaccinated per 100k,New Death vaccinated,New Death expired Vaccination,...,Severe cases Not vaccinated,Severe cases vaccinated per 100k,Severe cases expired Vaccination per 100k,Severe cases Not vaccinated per 100k,New Severe cases vaccinated,New severe cases expired Vaccination,New severe cases Not vaccinated,New severe cases vaccinated per 100k,New severe cases expired Vaccination per 100k,New severe cases Not vaccinated per 100k
0,2021-01-17,60+,0,0,243,0.0,0.0,51.4,0,0,...,555,0.0,0.0,117.4,0,0,58,0.0,0.0,12.3
1,2021-01-17,All population,1,0,4729,3.9,0.0,66.3,0,0,...,805,0.0,0.0,11.3,0,0,94,0.0,0.0,1.3
2,2021-01-17,0-59,1,0,4450,6.4,0.0,66.9,0,0,...,250,0.0,0.0,3.8,0,0,36,0.0,0.0,0.5
3,2021-01-18,All population,6,0,8738,13.2,0.0,123.8,0,0,...,792,2.2,0.0,11.2,1,0,99,2.2,0.0,1.4
4,2021-01-18,0-59,2,0,8309,7.9,0.0,126.0,0,0,...,235,0.0,0.0,3.6,0,0,33,0.0,0.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,2021-11-06,All population,26,19,149,0.5,2.1,4.8,0,0,...,146,0.4,1.0,4.7,1,1,3,0.0,0.1,0.1
881,2021-11-06,60+,5,1,3,0.4,1.0,2.4,0,0,...,67,1.3,3.8,54.3,1,0,1,0.1,0.0,0.8
882,2021-11-07,0-59,51,56,360,1.3,7.1,12.1,0,0,...,77,0.1,0.6,2.6,0,0,0,0.0,0.0,0.0
883,2021-11-07,All population,58,62,367,1.1,7.0,11.9,0,0,...,137,0.4,1.0,4.4,2,0,1,0.0,0.0,0.0
884,2021-11-07,60+,7,6,6,0.5,5.8,4.9,0,0,...,60,1.3,3.9,48.8,2,0,1,0.2,0.0,0.8

In [15]:
df1.columns

Index(['Date', 'age group', 'New cases vaccinated',
       'New cases expired Vaccination  ', 'New cases Not vaccinated',
       'New cases vaccinated per 100k',
       'New cases expired Vaccination  per 100k',
       'New cases Not vaccinated per 100k', 'New Death  vaccinated',
       'New Death  expired Vaccination  ', 'New Death  Not vaccinated',
       'New Death  vaccinated per 100k',
       'New Death  expired Vaccination  per 100k',
       'New Death  Not vaccinated per 100k', 'Severe cases vaccinated',
       'Severe cases expired Vaccination  ', 'Severe cases Not vaccinated',
       'Severe cases vaccinated per 100k',
       'Severe cases expired Vaccination  per 100k',
       'Severe cases Not vaccinated per 100k', 'New Severe cases vaccinated',
       'New severe cases expired Vaccination',
       'New severe cases Not vaccinated',
       'New severe cases vaccinated per 100k',
       'New severe cases expired Vaccination  per 100k',
       'New severe cases Not vaccinated per 100k'],
      dtype='object')

In [16]:
df1.drop(['New cases vaccinated per 100k','New cases expired Vaccination  per 100k','New cases Not vaccinated per 100k','New Death  vaccinated per 100k','New Death  expired Vaccination  per 100k','New Death  Not vaccinated per 100k','Severe cases expired Vaccination  per 100k','New severe cases vaccinated per 100k','New severe cases expired Vaccination  per 100k','New severe cases Not vaccinated per 100k','Severe cases vaccinated per 100k','Severe cases Not vaccinated per 100k'],axis = 1,inplace=True)

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 885 entries, 0 to 884
Data columns (total 14 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  885 non-null    datetime64[ns]
 1   age group                             885 non-null    object
 2   New cases vaccinated                  885 non-null    int64
 3   New cases expired Vaccination         885 non-null    int64
 4   New cases Not vaccinated              885 non-null    int64
 5   New Death  vaccinated                 885 non-null    int64
 6   New Death  expired Vaccination        885 non-null    int64
 7   New Death  Not vaccinated             885 non-null    int64
 8   Severe cases vaccinated               885 non-null    int64
 9   Severe cases expired Vaccination      885 non-null    int64
 10  Severe cases Not vaccinated           885 non-null    int64
 11  New Severe cases vaccinated           885 non-null    int64
 12  New severe cases expired Vaccination  885 non-null    int64
 13  New severe cases Not vaccinated       885 non-null    int64
dtypes: datetime64[ns](1), int64(12), object(1)
memory usage: 103.7+ KB

In [18]:
now = datetime.now()

current_time = now.strftime("%d_%m_%Y_%H_%M")
print("Current Time =", current_time)

filename = 'corona'+ current_time +'.csv'
with open(filename,mode='w',encoding='UTF-16',newline='') as rawdata_file:
    header = df1.columns
    writer = csv.writer(rawdata_file)
    writer.writerow(header)
    
    for row,row_data in df1.iterrows():
        writer.writerow(row_data)

Current Time = 03_08_2022_18_10

In [19]:
allpop = df1[df1['age group'] == 'All population']

In [20]:
now = datetime.now()

current_time = now.strftime("%d_%m_%Y")
print("Current Time =", current_time)

filename = 'allpopcorona'+ current_time +'.csv'
with open(filename,mode='w',encoding='UTF-16',newline='') as rawdata_file:
    header = allpop.columns
    writer = csv.writer(rawdata_file)
    writer.writerow(header)
    
    for row,row_data in allpop.iterrows():
        writer.writerow(row_data)

Current Time = 03_08_2022

In [21]:
notallpop = df1[df1['age group'] != 'All population']

In [22]:
now = datetime.now()

current_time = now.strftime("%d_%m_%Y")
print("Current Time =", current_time)

filename = 'notallpopcorona'+ current_time +'.csv'
with open(filename,mode='w',encoding='UTF-16',newline='') as rawdata_file:
    header = notallpop.columns
    writer = csv.writer(rawdata_file)
    writer.writerow(header)
    
    for row,row_data in notallpop.iterrows():
        writer.writerow(row_data)

Current Time = 03_08_2022

In [24]:
df2 = df1[df1['Date'] != ("%d_%m_%Y_%H_%M")]

In [25]:
df2

,Date,age group,New cases vaccinated,New cases expired Vaccination,New cases Not vaccinated,New Death vaccinated,New Death expired Vaccination,New Death Not vaccinated,Severe cases vaccinated,Severe cases expired Vaccination,Severe cases Not vaccinated,New Severe cases vaccinated,New severe cases expired Vaccination,New severe cases Not vaccinated
0,2021-01-17,60+,0,0,243,0,0,25,0,0,555,0,0,58
1,2021-01-17,All population,1,0,4729,0,0,30,0,0,805,0,0,94
2,2021-01-17,0-59,1,0,4450,0,0,5,0,0,250,0,0,36
3,2021-01-18,All population,6,0,8738,0,0,26,1,0,792,1,0,99
4,2021-01-18,0-59,2,0,8309,0,0,8,0,0,235,0,0,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,2021-11-06,All population,26,19,149,0,0,0,19,9,146,1,1,3
881,2021-11-06,60+,5,1,3,0,0,0,17,4,67,1,0,1
882,2021-11-07,0-59,51,56,360,0,0,0,2,5,77,0,0,0
883,2021-11-07,All population,58,62,367,0,0,2,19,9,137,2,0,1
884,2021-11-07,60+,7,6,6,0,0,2,17,4,60,2,0,1